site_name: anthonydurot.github.io
site_author: Anthony Durot
site_description: >-
    Anthony Durot

site_url: https://teddywarner.org/

repo_url: https://github.com/Twarner491/TeddyWarner.org
repo_name: Twarner491/TeddyWarner.org

copyright: >
  Copyright &copy; 2024 Anthony Durot

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anthonydurot
      name: Github - anthonydurot
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anthony-durot-9a0354138/
      name: Linked In - Anthony Durot
    - icon: fontawesome/solid/paper-plane
      link: mailto:<adurot.pro@gmail.com>
      name: Email - adurot.pro@gmail.com

  #analytics:
  #  provider: google
  #  property: !ENV GOOGLE_ANALYTICS_KEY

  consent:
    title: 🍪 Cookie Consent
    description: >- 
      anthonydurot.github.org uses cookies to recognize your repeated visits and preferences, 
      as well as to measure the effectiveness of my documentation and whether users
      find what they're searching for. With your consent, you're helping me to
      make my documentation better. Thank you!

theme:
  name: material
#  custom_dir: overrides

  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  language: en

  font:
    text: Fira Sans
    code: Ubuntu Mono

  logo: images/TeddyWarner.svg

  favicon: images/TW.svg

  icon:
    repo: fontawesome/brands/git-alt
                          
  features:
   - navigation.instant
   - navigation.tracking
   - navigation.top
   - navigation.tabs
   - navigation.expand
   - content.code.annotate
   - search.share
   - search.suggest
   - content.tabs.link
   - announce.dismiss

plugins:
  #- social
  #- material/search
  #- tags

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.details
  - extra
  - smarty
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - footnotes
  - abbr
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  #- social:
   #   cards: !ENV [CARDS, false]
   #   cards_font: Fira Sans
    #  cards_color:
    #    fill: "#5466CE" 
     #   text: "#FFFFFF"

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/index.js 
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home : http://teddywarner.com
  - About : About-Me/about.md
  - Projects:  http://teddywarner.com/feed/
  - Machine Profiles: 
    - Laser Cutters :
      - Epliog Fusion Pro 48 : Machine-Profiles/FusionPro48.md
    - 3D Printers : 
      - Prusa I3 MK3S+ : Machine-Profiles/MK3S+.md
      - Klipper Enabled Ender 3 : Machine-Profiles/KlipperEnder3Profile.md
  - Fab Academy: "http://fabacademy.org/2021/labs/charlotte/students/theodore-warner/"